### ISSUE TITLE
Compilation error with ESP32 MSBFIRST

### ISSUE THREAD

**Issue by 1technophile** [sparkfun/SparkFun_BME280_Arduino_Library#13]
With version 1.2.0 of the library I get the following error at compilation time:
error: 'MSBFIRST' was not declared in this scope
I'm using the latest arduino ESP32 env

If I add #include <Arduino.h> into the SparkFunBME280.cpp the compilation works
See also:
https://github.com/platformio/platform-espressif32/issues/34

**Comment by nseidle** [comment]
Thanks! This has been moved to the SparkFuBME280.h file.
