### ISSUE TITLE
Error compiling Arduino 1.8.5

### ISSUE THREAD

**Issue by markuspmeyer** [sparkfun/SparkFun_BME280_Arduino_Library#14]
Arduino 1.8.5

[SparkFunBME280.cpp.patch.gz](https://github.com/sparkfun/SparkFun_BME280_Arduino_Library/files/1609907/SparkFunBME280.cpp.patch.gz)

**Comment by nseidle** [comment]
Hi Mark, 

Can you extrapolate on your error? I (:blush:) can't work with a .patch.gz file.

We have a new version rolling out right now. Please try the new version of the lib if you can. Examples were all tested in v1.8.5.
