### ISSUE TITLE
sensor on i2c with 0x76 address doesn't work since update

### ISSUE THREAD

**Issue by LukaGitH** [sparkfun/SparkFun_BME280_Arduino_Library#21]
It stopped working with 2.0, works fine in 1.2

**Comment by nseidle** [comment]
Hi Luka - *Thank you* for checking my work! Please have a look at the latest commit. I've updated example 2 (I was trying to do too much in one example). I've tested on both RedBoard and Teensy and should be good to go. 

I've also added an advanced example 9 that uses software I2C. It's a bit of a hack job, and requires the user to edit the SparkFunBME280.h file but I'd welcome your feedback.

Additionally, I've added a basic SPI example.

Once you give me the green light I'll push a release so the library manager will increment.

**Comment by LukaGitH** [comment]
The problem is still here, sensor witn 0x76 can't be read. Even the old I2C_and_SPI_Multisensor which for mySensorB changed to:

mySensorB.settings.commInterface = I2C_MODE;
mySensorB.settings.I2CAddress = 0x76;

Is not working, while in 1.2 version it works fine. Therefor I think the problem is library still

Program Started
Starting BME280s... result of .begin():
Sensor A: 0x60
Sensor B: 0x58
Temperature: 21.91, 0.00 degrees C
Temperature: 71.44, 32.00 degrees F
Pressure: 95971.60, 0.00 Pa
Altitude: 470.81, 45846.20m
Altitude: 1544.65, 150414.04ft

**Comment by nseidle** [comment]
What platform are you compiling on? What platform are you compiling for?

**Comment by LukaGitH** [comment]
Arduino, pro mini at this point

**Comment by nseidle** [comment]
It works fine for me. Pro Mini, 3.3V @ 8MHz. I am using the BME280 on our [Combo board](https://www.sparkfun.com/products/14348).

![image](https://user-images.githubusercontent.com/117102/37879224-4d350194-3032-11e8-8e3a-5088724dabe7.png)

What board are you using? If you're using our [BME280 breakout](https://www.sparkfun.com/products/13676) did you close the jumper on the back of the board?

**Comment by nseidle** [comment]
Neat! Ok, have you pulled the SDO pin to ground, before powering the device, to set the address to 0x76?

**Comment by LukaGitH** [comment]
Yes, SDO is always ground on one, while Vcc on other. Like I said, hardware didn't change, only software did.

**Comment by nseidle** [comment]
Hmm. [This delay](https://github.com/sparkfun/SparkFun_BME280_Arduino_Library/blob/master/src/SparkFunBME280.cpp#L64) was delay(10) in the original library. Please try changing that from 2 to 10 and see if it fixes your problem?

**Comment by LukaGitH** [comment]
I think I have worked it out. It is not delay, since there was no delay before. Delay can stay at 2ms.
What the problem is, is this: 
```
BME can be 0x76 or 0x77
BMP can be only 0x77
```

BME has ID 0x60, BMP has ID 0x58 (mass production, samples have different ID)

in CPP, you check for 
`if(chipID != 0x60) return(chipID); //Failed!`
Which fails in case of BMP, so to fix this, this needs to be changed to
```
if(chipID != 0x60) // This is not BME
if(chipID != 0x58) // This is not BMP
return(chipID); //Failed!
```
So does 
`if(begin() == 0x60) return(true); //Begin normal init with these settings. Should return chip ID of 0x60
	return(false);`

to
if(begin() == 0x58) return(true); //Begin normal init with these settings. Should return chip ID of 0x58
if(begin() == 0x60) return(true); //Begin normal init with these settings. Should return chip ID of 0x60
	`return(false);`

**Comment by LukaGitH** [comment]
No, my BMP are mass production, 0x58
From datasheet, BME doesn't samples. 

Sure! It's my first time, hope I get it right

**Comment by nseidle** [comment]
Ah, now I understand. This library is written for the BME280, you're using the BMP280. If you want to submit a PR to allow the library to work with both BME and BMP I'm happy to have a look. I'm closing this because this is not really an issue with the library.

**Comment by sonybansi** [comment]
HW-611difficult to figure out which sense is this.
I think this is a fake BMP280.
What do you think 🤔
Can this read humidity?

**Comment by AndyEngland521** [comment]
@sonybansi Can you clarify what sensor you think is fake? Also, this library is for the BME280 instead of the BMP...

**Comment by sonybansi** [comment]
@AndyEngland521 
> 

> HW-611difficult to figure out which sense is this.
> I think this is a fake BMP280.
> What do you think 🤔
> Can this read humidity?
> 
> ![BMP280](https://user-images.githubusercontent.com/28208396/79898208-2b0cfe80-840b-11ea-9d62-c9e2342b191b.jpg)

**Comment by AndyEngland521** [comment]
Oh, the picture wasn't showing up for me for some reason. I am not sure which sensor you have, read the chipid as described above to determind which sensor you have.
