### ISSUE TITLE
Barometric pressure different from pro weather statuions

### ISSUE THREAD

**Issue by eduardcabanas** [sparkfun/SparkFun_BME280_Arduino_Library#29]
Hi 

I'm using Sparkfun bme280 library to read temp, hum & pressure, but for example reads 984 when the official weather station is 1005 

Do I have to calibrate or something? 

Thank's

**Comment by nseidle** [comment]
Sounds like it is very close. There are a variety of things that can affect the local pressure versus a official station:

* Your sensor may be higher/lower in altitude than the station
* The station may be displaying a [modified pressure](https://us.flukecal.com/blog/zeroing-barometric-pressure-local-airport)
