### ISSUE TITLE
.begin() get hanging if BME280 failure

### ISSUE THREAD

**Issue by tbdltee** [sparkfun/SparkFun_BME280_Arduino_Library#9]
I simulate BME280 failure by remove Vcc out of the sensor. The code get hanging when I call .begin(). There  should be a way to improve the code by testing the BME280 and return result to the . begin().
/tee

**Comment by nseidle** [comment]
I can't quite replicate your failure but I like the premise of your idea. I have added 

	uint8_t chipID = readRegister(BME280_CHIP_ID_REG); //Should return 0x60
	if(chipID != 0x60) return(chipID); //Failed!

This is a check in .begin() to make sure the sensor is successfully connected before we start reading calibration values. If it fails to get 0x60, then .begin() returns and the user can decide what to do.
